### ISSUE TITLE
Next and previous buttons not advancing

### ISSUE THREAD

**Issue by coevolving** [hibbitts-design/grav-theme-bootstrap4-open-matter#12]
Thanks for all of your work on this theme, @paulhibbitts .  It's great!

I had found a mention of how the next and previous button worked at https://discourse.getgrav.org/t/previous-page-next-page/11272 .  My understanding was that it's already built into the theme.

If you look at http://coevolving.com/commons/20211107-csrp-systems-changes-learning , you'll see that the next and previous buttons aren't working.  This actually isn't a blog series, it content that is indexed at http://coevolving.com/commons/publications .  (I moved over a site from Drupal where the URLs followed a flat rather than hierarchical structure, and wanted to preserve those links).

Here is the header from the file item.md for that entry.

```
---
title: '2021/11/07 Progress on Systems Changes Learning: Coevolving towards Rethinking Systems Thinking'
hide_page_title: false
show_sidebar: true
hide_git_sync_repo_link: false
content:
    items: '@self.siblings'
    order:
        by: title
        dir: desc
visible: false
date: '2021-11-07 00:00'
hide_from_post_list: false
continue_link: true
taxonomy:
    category:
        - publication
admin:
    children_display_order: collection
---

<h3>Authors</h3>
```

Could you please advise if I need to make some additional customizations to make the "next" and "previous" buttons work?  Let me know I should provide you with more information.

**Comment by paulhibbitts** [comment]
Hi @coevolving , glad you are finding the theme useful!

Looking at your page frontmatter my hunch is that you need to include a `blog` category for the Next/Prev buttons to work, here is an example of that at work: https://raw.githubusercontent.com/hibbitts-design/blog-hibbitts-design-org/master/pages/01.posts/2022-03-11-a-few-thoughts-about-the-new-toc-feature-for-my-docsify-projects/item.md

If I recall correctly, the Pagination plugin has options to change this, but I think I just used the default options myself in my skeletons etc.

Please let me know if this works!, cheers.
Paul

**Comment by paulhibbitts** [comment]
Hmm.. it has been a while since I've work on this theme but also there is the issue of the page collector in the top-level page that could be involved, what does your frontmatter look like there? Here is an example: https://raw.githubusercontent.com/hibbitts-design/blog-hibbitts-design-org/master/pages/01.posts/blog.md

**Comment by coevolving** [comment]
I actually was changing the entries from item.md to blog.md through the GUI, rather than directly.  I wasn't changing categories.

(3) Let me trying leaving the page template as item.md , and modifying the category to blog on two entries.

The first item.md entry has header:

```
---
title: '2022/03/04 Systems Thinking through Changes'
hide_page_title: false
show_sidebar: true
hide_git_sync_repo_link: false
content:
    items: '@self.siblings'
    order:
        by: title
        dir: desc
visible: false
date: '2022-03-04 00:00'
hide_from_post_list: false
continue_link: true
taxonomy:
    category:
        - blog
admin:
    children_display_order: collection
---

<h3>Authors</h3>
```
The second item.md entry has ...

```
---
title: '2022/01/10 Living, Becoming, Process Philosophy:  Systems Thinking in Time'
hide_page_title: false
show_sidebar: true
hide_git_sync_repo_link: false
content:
    items: '@self.siblings'
    order:
        by: title
        dir: desc
visible: false
date: '2022-01-10 18:00'
hide_from_post_list: false
continue_link: true
taxonomy:
    category:
        - blog
admin:
    children_display_order: collection
---

<h3>Discussion Leader</h3>
```
Unfortunately, no joy.  The next and previous don't work.

(4) The header in the page.md for http://coevolving.com/commons/publications looks like ...

```
---
title: Publications
hide_page_title: false
show_sidebar: true
hide_git_sync_repo_link: false
visible: true
content:
    items: '@self.siblings'
    order:
        by: date
        dir: asc
sections_nav_align: right
hide_next_prev_page_buttons: false
hide_from_post_list: false
continue_link: true
---

<table border="0" rules="rows">
```

And if I change that page.md into a blog.md , then I get the effect from (2), above.
